# Generated by Django 2.0.7 on 2018-10-31 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fashion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fash_question', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='Publication Date')),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_choice', models.CharField(max_length=200)),
                ('style_pick', models.IntegerField(default=0)),
                ('fashion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ballyapp.Fashion')),
            ],
        ),
    ]
